### ISSUE TITLE
Multi devices

### ISSUE THREAD

**Issue by JLFN** [torrottum/ikea-ansluta-esphome#6]
Hey
Can you please make an example when you have multi ansluta/utrusta.
I have 2 different units with 2 different remotes.

**Comment by torrottum** [comment]
Hi
You need to find the addresses for your remotes. This can be done by either by viewing the logs or listening to the topic `ikea_ansluta/light/+/state` and clicking your remotes. Then you add one light for each remote in HA.

**Comment by torrottum** [comment]
Just want to give a heads up, I'm in the process of refactoring this to a proper custom component for esphome. Using the API instead of MQTT. It will also support 50% brightness: #7

Should make the setup a bit easier

**Comment by torrottum** [comment]
I'm closing this. I have an example of how to use multiple remotes with the custom component [here](https://github.com/torrottum/ikea-ansluta-esphome/blob/d15cb0a804d3087916bcf04518b84be4fba08075/example/ikea_ansluta_example.yaml).

If you need to migrate from 0.1.x of this repo, see the upgrade guide: https://github.com/torrottum/ikea-ansluta-esphome#upgrading-from-01x-to-100

I've added a comment on #10 explaining how you continue to use MQTT with the custom component
